site_name: Kudos Docs
site_description: Enterprise productivity solutions
site_author: Andrew Reynolds
site_url: https://docs.kudosapps.com/
repo_url: https://www.kudosapps.com
repo_name: kudosapps.com

extra:
  social:
    - type: "github"
      link: "https://github.com/isw-kudos"
    - type: "twitter"
      link: "https://twitter.com/kudosbadges"
    - type: "linkedin"
      link: "https://www.linkedin.com/company/isw_2/about/"
    - type: "youtube"
      link: "https://www.youtube.com/channel/UC_9nMUcp6jcweQZML2qIy8A"
nav:
  - Welcome: index.md
  # - Kudos Analytics:
  #   - Installation:
  #     - FAQ: analytics/websphere-faq.md
  # - Kudos Badges:
  #   - Installation:
  #     - FAQ: badges/websphere-faq.md
  - Kudos Boards:
      - Versions: boards/index.md
      - Boards Cloud:
          - Overview: https://info.kudosboards.com
          - Integrations:
              - IBM Connections Cloud: boards/cloud.md
              - IBM Connections On-Prem:
                  - Authentication: boards/connections/auth-hybrid.md
                  - Connections Header: boards/connections/header-hybrid.md
                  - Connections Apps Menu: boards/connections/apps-menu-hybrid.md
                  - Connections Widgets: boards/connections/widgets-hybrid.md
              - IBM Verse: boards/verse/addin-hybrid.md
              - Office 365 for Business:
                  - Overview: boards/msgraph/overview.md
                  - App Tile: boards/msgraph/custom-tiles.md
                  - Teams Integration: boards/msgraph/teams.md
                  - Outlook Plugin: boards/msgraph/outlook.md
                  - Sharepoint Pages: boards/msgraph/sharepoint.md
              - Auth0: boards/auth0/index.md
      - Boards Docker:
          - For Kubernetes: boards/kubernetes.md
          - For Swarm: boards/swarm.md
          - Common Config:
            - Environment: boards/env/common.md
            - Team Logins: boards/env/teams.md
          - Integrations:
              - IBM Connections On-Prem:
                  - Authentication: boards/connections/auth-on-prem.md
                  - Connections Header: boards/connections/header-on-prem.md
                  - Connections Apps Menu: boards/connections/apps-menu-on-prem.md
                  - Connections Widgets: boards/connections/widgets-on-prem.md
                  - Web Server Config: boards/connections/httpd.md
              - IBM Verse: boards/verse/addin-on-prem.md
      - Boards Hybrid: boards/hybrid.md
      - Troubleshooting:
          - Boards Hybrid: boards/troubleshooting/conn-hybrid.md
          - Boards Docker: boards/troubleshooting/conn-on-prem.md
          - Boards WebSphere: boards/troubleshooting/websphere.md
          - Office 365 for Business: boards/troubleshooting/office365.md
      - How To Guide:
          - Knowledge Base & Support: boards/howto/knowledgebase.md
          - Getting Started with Kudos Boards: boards/howto/getting-started-with-kudos-boards.md
          - Adding Boards to Microsoft Teams: boards/howto/adding-boards-to-teams.md
          - Using IBM Verse with Kudos Boards: boards/howto/use-verse.md
          - Using Auth0 with Kudos Boards: boards/howto/use-auth0.md
          - Quick Tips for Boards: boards/howto/quick-tips-for-boards.md
          - Accessing Global Templates: boards/howto/accessing-global-templates.md
          - Adding Members to a Board: boards/howto/adding-members-to-a-board.md
          - Timeline View in Boards: boards/howto/timeline-view-in-boards.md
          - Mind Map View: boards/howto/mind-map-view.md
          - Creating Templates: boards/howto/creating-templates.md
          - Archiving and Restoring: boards/howto/archiving-and-restoring.md
          - Permissions in Kudos Boards: boards/howto/permissions.md

  - Kudos Ideas:
      - How To Guide: ideas/howto.md
      - Connections Cloud: ideas/cloud-setup.md
  - Buzzy:
      - Overview: buzzy/index.md
      - Installation:
          - IBM ICP (Kubernetes): buzzy/buzzy-icp.md
          - WAS Config: buzzy/buzzy-wasconfig.md
          - Connections Widgets: buzzy/buzzy-widgets.md
  - Docker Swarm:
      - Installation: swarm/index.md
      - Storage: swarm/storage.md
      # - Advanced: swarm/advanced.md
      - Troubleshooting: swarm/troubleshooting.md
  # - Kubernetes:
  # - Installation: kubernetes/index.md
  # - Advanced: kubernetes/advanced.md
  # - Troubleshooting: kubernetes/troubleshooting.md

markdown_extensions:
  - toc:
      permalink: true

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: orange
    accent: light blue
  favicon: assets/images/favicon.ico
  logo:
    icon: local_library

extra_css:
  - "/assets/css/custom.css"

google_analytics:
  - "UA-1747668-5"
  - "auto"
